### ISSUE TITLE
Support for container queries

### ISSUE THREAD

**Issue by Dgcim1** [mr150/mlut#51]
Is there any plan to support for [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries)? Browser support is already [good enough](https://caniuse.com/css-container-queries).

**Comment by mr150** [comment]
Hi there. Yes, we are currently working on a big release that will have JIT mode and add container queries in it as well

But you don't have to wait and add basic support yourself, right in your config! See the example below:
```scss
@use 'sass:map';
@use 'sass:meta';

@use 'mlut/tools' as ml with (
  $utils-data: (
    'utils': (
      'registry': (
        'Ctnt': (
          'properties': container-type,
          'keywords': (
            'is': inline-size,
          ),
        ),
      ),
    ),
  ),
  $at-rules-data: (
    'container': (
      'alias': 'c',
    ),
  ),
);

// using at-rule converter from @supports
ml.$at-rules-db: map.set(
  ml.$at-rules-db,
  'container',
  'converter',
  meta.get-function('convert-ar-supports', false, ml),
);

@include ml.apply('@c:mnw600_P5u Ctnt-is');
```
CSS output:
```css
@container (min-width: 600px) {
  .\@c\:mnw600_P5u {
    padding: 1.25rem;
  }
}
.Ctnt-is {
  container-type: inline-size;
}
```
